### ISSUE TITLE
如何集成非OPENAI的模型？

### ISSUE THREAD

**Issue by wenmhan** [web-infra-dev/midscene#186]
如 qwen等其他模型？

**Comment by yuyutaotao** [comment]
Midscene 内置的是 OpenAI SDK ，可以参考配置连接其他 endpoint :  https://midscenejs.com/zh/model-provider.html

如果需要内置其他 SDK ，可以具体提出来看看

**Comment by ayiaq1** [comment]
模型切换能否以插件的形式暴露出来，让外部自己开发插件？

**Comment by wenmhan** [comment]
> Midscene 内置的是 OpenAI SDK ，可以参考配置连接其他 endpoint : https://midscenejs.com/zh/model-provider.html
> 
> 如果需要内置其他 SDK ，可以具体提出来看看


使用的是 阿里 qwen-max模型；使用文档中设置的 nodejs 调用示例为：

import OpenAI from "openai";

const openai = new OpenAI(
    {
        // 若没有配置环境变量，请用百炼API Key将下行替换为：apiKey: "sk-xxx",
        apiKey: process.env.DASHSCOPE_API_KEY,
        baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    }
);

async function main() {
    const completion = await openai.chat.completions.create({
        model: "qwen-plus",  //模型列表：https://help.aliyun.com/zh/model-studio/getting-started/models
        messages: [
            { role: "system", content: "You are a helpful assistant." },
            { role: "user", content: "你是谁？" }
        ],
    });
    console.log(JSON.stringify(completion))
}

main();

**Comment by yuyutaotao** [comment]
我没懂，按上面的文档示例，Midscene 提供的环境变量配置应该已经足够用来接入了才对？不需要什么开发，只要配置

**Comment by wenmhan** [comment]
> 我没懂，按上面的文档示例，Midscene 提供的环境变量配置应该已经足够用来接入了才对？不需要什么开发，只要配置


windows 环境：
环境变量>> 系统变量 中已添加
OPENAI_API_KEY sk-xxxxxxxxxxx
OPENAI_BASE_URL  https://dashscope.aliyuncs.com/compatible-mode/v1
MIDSCENE_MODEL_NAME qwen-max

在 playwright-demo 项目运行 ： npx playwright test ./e2e/online-order-zh.spec.ts

报错信息为：
![Image](https://github.com/user-attachments/assets/018746fe-ab19-4a9e-a2c1-3428a59b1400)
---
 npx playwright test ./e2e/online-order-zh.spec.ts


Running 1 test using 1 worker
[chromium] › online-order-zh.spec.ts:9:5 › ai online order


  1) [chromium] › online-order-zh.spec.ts:9:5 › ai online order ────────────────────────────────────

    Error: 500 <500> InternalError.Algo: 'NoneType' object is not iterable
    Error: 500 <500> InternalError.Algo: 'NoneType' object is not iterable

        at Function.generate (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\corsrc\error.ts:98:14)
        at OpenAI.makeStatusError (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscenenai\src\core.ts:397:21)
        at OpenAI.makeRequest (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\co\src\core.ts:460:24)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at call (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\in
        at callToGetJSONObject (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\c5533:20)
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\li
        at plan (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\in
        at Object.executor (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\d24)
        at Executor.flush (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\d25)
        at PageTaskExecutor.action (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscejs:1418:26)
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\we86:26)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@playwright\test\node_modules\plstType.js:236:24
        at TestTypeImpl._step (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@playwright\wright\lib\common\testType.js:234:12)
        at Function.generate (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\corore\node_modules\openai\src\error (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscenr.ts:98:14)                                                                                               co
        at OpenAI.makeStatusError (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscinene\core\node_modules\openai\srcD:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\c\core.ts:397:21)                                                                                          li
        at OpenAI.makeRequest (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\incore\node_modules\openai\src\coraily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\de.ts:460:24)                                                                                              \d
        at call (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\ceindex.js:5485:22)                                                                                         we
        at callToGetJSONObject (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscenes:\core\dist\lib\index.js:5533:20):\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\we
                                                                                                          s:
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\        at Function.generate (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\node_modules\op\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\ayenai\src\error.ts:98:14)
        at OpenAI.makeStatusError (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\node_modul1342:24)     
es\openai\src\core.ts:397:21)
        at OpenAI.makeRequest (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\aycore\node_modules\oExecutor.action (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midspenai\src\core.ts:460:24)
        at call (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5485:22)  t.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\        at callToGetJSONObject (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\inde File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.jx.js:5533:20)
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5565:3js:1791:13)  
        at OpenAI.makeRequest (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\nodat plan (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\e_modules\openai\src\core.ts:460:24)
        at call (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.jsb\index.js:ile updated: D:\Daily File\code\midscene-example\playwright-demo\midscene_run\report\pl:5485:22)
        at callToGetJSONObject (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dib\index.js:g slow test files to speed up parallel execution
st\lib\index.js:5533:20)
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\inde\dist\lib\iile updated: D:\Daily File\code\midscene-example\playwright-demo\midscene_run\report\plx.js:5565:32)
        at plan (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js\lib\index.de\midscene-example\playwright-demo\e2e>
        at OpenAI.makeRequest (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core    at Object.executor (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\node_modules\openai\src\core.ts:460:24)
        at call (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\inde    at Executor.flush (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\corex.js:5485:22)
        at callToGetJSONObject (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\cor    at PageTaskExecutor.action (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midse\dist\lib\index.js:5533:20)
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\    at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\index.js:5565:32)
        at plan (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\inde    at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.j        at OpenAI.makeRequest (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\node_modules\openai\src\core.ts:460:24)
        at call (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5485:22)
        at callToGetJSONObject (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5533:20)
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5565:32)
        at plan (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5856:30)
        at Object.executor (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1342:24)
        at Executor.flush (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:4607:25)
        at PageTaskExecutor.action (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1418:26)
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1786:26)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1791:13)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
re\node_modules\openai\src\core.ts:460:24)
        at call (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5485:22)
        at callToGetJSONObject (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5533:20)
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5565:32)
        at plan (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5856:30)
        at Object.executor (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1342:24)
        at Executor.flush (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:4607:25)
        at PageTaskExecutor.action (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1418:26)
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1786:26)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1791:13)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at call (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5485:22)
        at callToGetJSONObject (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5533:20)
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5565:32)
        at plan (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5856:30)
        at Object.executor (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1342:24)
        at Executor.flush (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:4607:25)
        at PageTaskExecutor.action (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1418:26)
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1786:26)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1791:13)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at callAiFn (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5565:32)
        at plan (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:5856:30)
        at Object.executor (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1342:24)
        at Executor.flush (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:4607:25)
        at PageTaskExecutor.action (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1418:26)
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1786:26)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1791:13)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at Executor.flush (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\core\dist\lib\index.js:4607:25)
        at PageTaskExecutor.action (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1418:26)
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1786:26)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1791:13)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at PageAgent.aiAction (D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1791:13)
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32
        at D:\Daily File\code\midscene-example\playwright-demo\node_modules\@midscene\web\dist\lib\index.js:1917:32


Midscene - report file updated: D:\Daily File\code\midscene-example\playwright-demo\midscene_run\report\playwright-merged-2024-12-  Slow test file: [chromium] › online-order-zh.spec.ts (20.1s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [chromium] › online-order-zh.spec.ts:9:5 › ai online order ─────────────────────────────────────

**Comment by yuyutaotao** [comment]
看起来 Midscene 已经跑起来了，但模型服务的返回不兼容，没看懂是个什么报错。

阿里云上的 qwen 我们还没测过兼容性...

**Comment by yuyutaotao** [comment]
实测了一下，qwen-vl-max-latest 应该是可以的。

你代码里用的 qwen-max 不支持图像输入，不适合在这个场景使用。

**Comment by gaomAndximi** [comment]
请问怎么能集成qianwen1.5，可以有一个具体的例子吗？

**Comment by wenmhan** [comment]
> 实测了一下，qwen-vl-max-latest 应该是可以的。
> 
> 你代码里用的 qwen-max 不支持图像输入，不适合在这个场景使用。

好的，已找到问题所在。替换多模态模型后正常。

**Comment by wenmhan** [comment]
> [@wenmhan](https://github.com/wenmhan)
> 
> text modal add dev params MIDSCENE_MODEL_TEXT_ONLY='true' ？

no ,just three params:
OPENAI_API_KEY sk-xxxxxxxxxxx
OPENAI_BASE_URL https://dashscope.aliyuncs.com/compatible-mode/v1
MIDSCENE_MODEL_NAME qwen-vl-max-latest

**Comment by yuyutaotao** [comment]
@729993031 text-only models doesn't perform well in Midscene. `MIDSCENE_MODEL_TEXT_ONLY ` is just an internal config for testing purpose.
