### ISSUE TITLE
执行操作异常

### ISSUE THREAD

**Issue by zjian95** [web-infra-dev/midscene#195]
Failed to plan actions with context: undefined
AssertionError [ERR_ASSERTION]: Failed to plan actions with context: undefined
    at Sr (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/popup.js:1:2816013)
    at async Object.executor (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/popup.js:1:2873406)
    at async Vt.flush (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/popup.js:1:2790577)
    at async N.action (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/popup.js:1:2874388)
    at async D.aiAction (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/popup.js:1:2878267)
    at async Object.onClick (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/popup.js:1:4005936)

**Comment by yuyutaotao** [comment]
操作浏览器的时候不要切换 tab，在 https:// 开头的页面中试试？
