### ISSUE TITLE
run demo failed, Error: 400 Missing required parameter: 'response_format.json_schema'. (request id: 202412201428294827994785579509)

### ISSUE THREAD

**Issue by hankunfang** [web-infra-dev/midscene#196]
/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/web/dist/lib/puppeteer.js:1291
throw new Error(`${errorTask == null ? void 0 : errorTask.error}
^

Error: 400 Missing required parameter: 'response_format.json_schema'. (request id: 202412201428294827994785579509)
Error: 400 Missing required parameter: 'response_format.json_schema'. (request id: 202412201428294827994785579509)
at Function.generate (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/openai/src/error.ts:70:14)
at OpenAI.makeStatusError (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/openai/src/core.ts:397:21)
at OpenAI.makeRequest (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/openai/src/core.ts:460:24)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async call (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:5530:22)
at async callToGetJSONObject (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:5576:20)
at async callAiFn (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:5608:32)
at async plan (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:5895:30)
at async Object.executor (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/web/dist/lib/puppeteer.js:839:24)
at async Executor.flush (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/core/dist/lib/index.js:4607:25)
at PuppeteerAgent.aiAction (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/node_modules/@midscene/web/dist/lib/puppeteer.js:1291:13)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async (/Users/hankunfang/workspace/midscene-example/puppeteer-demo/demo.ts:28:5)

**Comment by yuyutaotao** [comment]
配置了什么模型？

**Comment by hankunfang** [comment]
export MIDSCENE_MODEL_NAME=gpt-4o

**Comment by yuyutaotao** [comment]
再看下 @midscene/web 的版本号？

如果已经是最近的 latest 或者 beta，应该是没问题的才对。是否是 API 平台的问题？

**Comment by hankunfang** [comment]
"devDependencies": {
        "@midscene/web": "^0.8.7",
        "dotenv": "^16.4.5",
        "puppeteer": "^23.11.1",
        "ts-node": "^10.9.2",
        "tsx": "^4.19.1"
    }

**Comment by hankunfang** [comment]
chrome 插件用相同的配置是ok的

**Comment by yuyutaotao** [comment]
试了一下，能跑通的，没排查思路了

能给我临时签发一个 token 来试跑么？ 发送到邮箱 yutao.tao # bytedance.com

**Comment by hankunfang** [comment]
刚问了公司，说没有临时的token。。。

**Comment by hankunfang** [comment]
这个是使用了哪个API？

**Comment by yuyutaotao** [comment]
我们刚在这个仓库里新增了可用性测试的目录：  

https://github.com/web-infra-dev/midscene-example/tree/main/connectivity-test

你可以把它的用例运行起来，看看是 API  本身可用性的问题 or Midscene 的问题。

**Comment by hankunfang** [comment]
DEV  v2.1.8 /Users/hankunfang/workspace/midscene-example/connectivity-test

(node:2437) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
stdout | tests/connectivity.test.ts
[dotenv@16.4.7][DEBUG] No encoding is specified. UTF-8 is used by default

 ✓ tests/connectivity.test.ts (3) 8562ms
   ✓ Use OpenAI SDK directly (2) 5234ms
     ✓ basic call 1503ms
     ✓ with image input 3731ms
   ✓ Use Midscene wrapped OpenAI SDK (1) 3327ms
     ✓ call to get json object 3327ms

 Test Files  1 passed (1)
      Tests  3 passed (3)
   Start at  09:53:24
   Duration  9.06s (transform 52ms, setup 0ms, collect 208ms, tests 8.56s, environment 0ms, prepare 60ms)

 PASS  Waiting for file changes...
       press h to show help, press q to quit

**Comment by yuyutaotao** [comment]
1. 更新到 v0.8.8 版本再试试
2. 脚本运行的时候帮忙判断一下，是 .ai 方法还是 .aiQuery 抛错的？
