### ISSUE TITLE
got 403 error while use ollama locally

### ISSUE THREAD

**Issue by leyangyp** [web-infra-dev/midscene#198]
start ollama serve locally
config the mdsecene wtih ollama:

```
OPENAI_BASE_URL=http://x.x.x.x:11434/v1/
OPENAI_API_KEY=ollama
MIDSCENE_MODEL_NAME=llama3.2-vision
```

got errors bellow: 
```
403 status code (no body)
Error: 403 status code (no body)
    at e.generate (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:1439512)
    at h.makeStatusError (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:1427989)
    at h.makeRequest (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:1429105)
    at async chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:2797459
    at async gr (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:2797308)
    at async _r (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:2798359)
    at async context (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:2821150)
    at async Nr.extract (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:2818947)
    at async Object.executor (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:2851372)
    at async Object.executor (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/playground-entry.js:1:2845169)
```

**Comment by yuyutaotao** [comment]
It looks like some server configuration issue : https://www.perplexity.ai/search/ollama-403-KQBhamiZT7CaxTy53cCBww

**Comment by purocean** [comment]
https://github.com/ollama/ollama/issues/2425

**Comment by leyangyp** [comment]
@purocean @yuyutaotao 

thanks very much

**Comment by yuyutaotao** [comment]
Thanks @purocean ! Seems this could solve the problem.
